// frontend/app/pages/auth/login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { initiateOAuthFlow } from '@/utils/oauth';

definePageMeta({
  layout: false,
  middleware: 'guest',
});

const { t } = useI18n();
const config = useRuntimeConfig();

const isRedirecting = ref(false);

async function handleLogin() {
  isRedirecting.value = true;
  await initiateOAuthFlow({
    authServerUrl: config.public.authServerUrl,
    clientId: config.public.oauthClientId,
    redirectUri: config.public.oauthRedirectUri,
    scopes: ['openid', 'profile', 'email'],
  });
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-muted/50">
    <Card class="w-full max-w-md">
      <CardHeader class="text-center">
        <div class="text-4xl mb-4">
          <Icon name="lucide:lock" class="size-12 mx-auto text-primary" />
        </div>
        <CardTitle class="text-2xl">
          {{ t('auth.login.title') }}
        </CardTitle>
        <CardDescription>
          {{ t('auth.login.subtitle') }}
        </CardDescription>
      </CardHeader>

      <CardContent class="space-y-6">
        <!-- Info Banner -->
        <Alert class="flex items-start gap-3">
          <Icon name="lucide:info" class="size-4 mt-0.5 shrink-0" />
          <AlertDescription class="flex-1">
            {{ t('auth.login.mockFormInfo') }}
          </AlertDescription>
        </Alert>

        <!-- Mock Form (Disabled) -->
        <div class="space-y-4">
          <div class="space-y-2">
            <Label>{{ t('auth.login.usernameLabel') }}</Label>
            <Input
              type="text"
              :placeholder="t('auth.login.usernamePlaceholder')"
              disabled
            />
          </div>
          <div class="space-y-2">
            <Label>{{ t('auth.login.passwordLabel') }}</Label>
            <Input
              type="password"
              :placeholder="t('auth.login.passwordPlaceholder')"
              disabled
            />
          </div>
          <Button class="w-full" disabled>
            {{ t('auth.login.usernameLoginButton') }}
          </Button>
        </div>

        <!-- Divider -->
        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <span class="w-full border-t" />
          </div>
          <div class="relative flex justify-center text-xs uppercase">
            <span class="bg-background px-2 text-muted-foreground">
              {{ t('auth.login.or') }}
            </span>
          </div>
        </div>

        <!-- OAuth Button -->
        <div class="space-y-2">
          <Button
            class="w-full"
            :disabled="isRedirecting"
            @click="handleLogin"
          >
            <template v-if="isRedirecting">
              <Icon name="lucide:loader-circle" class="size-4 animate-spin" />
              {{ t('auth.login.redirecting') }}
            </template>
            <template v-else>
              {{ t('auth.login.oauthButton') }}
            </template>
          </Button>
        </div>
      </CardContent>
    </Card>
  </div>
</template>

// examples/oauth-client-spa/src/routes/login.tsx
import { createFileRoute, Navigate, useSearch } from '@tanstack/react-router';
import { Shield } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { useAuthStore } from '@/lib/auth';

interface LoginSearch {
  returnTo?: string;
}

export const Route = createFileRoute('/login')({
  validateSearch: (search: Record<string, unknown>): LoginSearch => ({
    returnTo: typeof search.returnTo === 'string' ? search.returnTo : undefined,
  }),
  component: LoginPage,
});

function LoginPage() {
  const { returnTo } = useSearch({ from: '/login' });
  const { isAuthenticated, login } = useAuthStore();

  if (isAuthenticated) {
    return <Navigate to={returnTo || '/'} />;
  }

  const handleOAuthLogin = () => {
    login(returnTo || '/');
  };

  return (
    <div className="flex min-h-[70vh] items-center justify-center">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Welcome Back</CardTitle>
          <CardDescription>
            Sign in to access protected resources
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Dummy login form (disabled) */}
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="user@example.com"
                disabled
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                disabled
              />
            </div>
            <Button className="w-full" disabled>
              Sign In
            </Button>
            <p className="text-center text-xs text-muted-foreground">
              Local authentication is disabled in this demo
            </p>
          </div>

          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <Separator className="w-full" />
            </div>
            <div className="relative flex justify-center text-xs uppercase">
              <span className="bg-card px-2 text-muted-foreground">
                Or continue with
              </span>
            </div>
          </div>

          {/* OAuth Login Button */}
          <Button
            variant="outline"
            className="w-full"
            onClick={handleOAuthLogin}
          >
            <Shield className="mr-2 h-4 w-4" />
            Login with Altalune
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
